# Generated by Django 5.0.4 on 2024-05-25 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='estado',
            new_name='Descripcion',
        ),
    ]
