# Generated by Django 5.0.4 on 2024-05-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0003_rename_descripcion_pedido_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
